### ISSUE TITLE
bug: Lifecycle Manager crash

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#1455]
### Description

The Lifecycle-Manager crashed on PROD.
Edit: The crash happened 2d5h before and has not appeared again since.

#### The relevant logs:
```
{"level":"ERROR","date":"2024-04-09T01:46:44.51764028Z","caller":"controller/controller.go:329","msg":"Reconciler error","context":{"controller":"kyma","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","Kyma":{"name":"10252593-c113-4a8e-b769-33cca498334a","namespace":"kcp-system"},"namespace":"kcp-system","name":"10252593-c113-4a8e-b769-33cca498334a","reconcileID":"d62cce52-281b-42ba-aefd-64131630a1df","error":"manifests still exist"},"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
fatal error: concurrent map iteration and map write

goroutine 386022856 [running]:
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue({0x2cea500?, 0xc0007ed5c0})
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:622 +0x285
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue({0x2cea500?, 0xc0007ed560})
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:623 +0x2b7
k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:608
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy(0xc0005fe2a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/unstructured.go:151 +0x58
github.com/kyma-project/lifecycle-manager/pkg/watcher.configureUnstructuredObject(0xc0654f55c0, 0xc0005fe2a0)
 ```

#### Extracted StackTrace:
```
- sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t
- /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\n
- sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t
- /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\n
- sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t
- /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227
```

#### The relevant snippet of the `controller-runtime` code:
```
316         result, err := c.Reconcile(ctx, req)
317         switch {
318         case err != nil:
319                 if errors.Is(err, reconcile.TerminalError(nil)) {
320                         ctrlmetrics.TerminalReconcileErrors.WithLabelValues(c.Name).Inc()
321                 } else {
322                         c.Queue.AddRateLimited(req)
323                 }
324                 ctrlmetrics.ReconcileErrors.WithLabelValues(c.Name).Inc()
325                 ctrlmetrics.ReconcileTotal.WithLabelValues(c.Name, labelError).Inc()
326                 if !result.IsZero() {
327                         log.Info("Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if th    e error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/control    ler-runtime/pkg/reconcile#Reconciler")
328                 }
329                 log.Error(err, "Reconciler error")
```

It looks the `Reconciler error` error in line 329 is caused by an error returned from line 316: `c.Reconcile(ctx, req)`

**Note: it may be that the last log entry is NOT related to an error, it's just the last thing controller logger managed to handle before failure. Just after producing that log entry the controller started to process ANOTHER item (not visible in the logs). And during processing of this another item it crashed because of "concurrent map iteration+write". Because the goroutine panicked, no log entry was produced. This would explain the strange format of the last line in the logs: No proper logger header/format, just the plain error message.**

#### The only `running` goroutine stack trace:
```
goroutine 386022856 [running]:
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue({0x2cea500?, 0xc0007ed5c0})
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:622 +0x285
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue({0x2cea500?, 0xc0007ed560})
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:623 +0x2b7
k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:608
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy(0xc0005fe2a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/unstructured.go:151 +0x58
github.com/kyma-project/lifecycle-manager/pkg/watcher.configureUnstructuredObject(0xc0654f55c0, 0xc0005fe2a0)
        /workspace/pkg/watcher/skr_webhook_resources.go:234 +0x2ac
github.com/kyma-project/lifecycle-manager/pkg/watcher.(*SKRWebhookManifestManager).getRawManifestClientObjects(0x33420bb?, 0xc0654f55c0)
        /workspace/pkg/watcher/skr_webhook_manifest_manager.go:209 +0xbf
github.com/kyma-project/lifecycle-manager/pkg/watcher.(*SKRWebhookManifestManager).getSKRClientObjectsForInstall(0xc000a74000, {0x38213a8, 0xc0cc81e540}, {0x7ea41523b618, 0xc0e67ebf68}, {{0xc0bc637006?, 0x0?}, {0xc0dd8507b0?, 0xc0e67ebf68?}}, {0x33420bb, ...}, ...)
        /workspace/pkg/watcher/skr_webhook_manifest_manager.go:186 +0x91
github.com/kyma-project/lifecycle-manager/pkg/watcher.(*SKRWebhookManifestManager).Install(0xc000a74000, {0x38213a8, 0xc0cc81e540}, 0xc0ddace1c0)
        /workspace/pkg/watcher/skr_webhook_manifest_manager.go:112 +0x473
github.com/kyma-project/lifecycle-manager/internal/controller.(*KymaReconciler).handleProcessingState.func3()
        /workspace/internal/controller/kyma_controller.go:393 +0x35
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 434
        /go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```

### Steps to reproduce

unknown. See the logs in the PROD environment

### Environment Type

Managed

### Environment Info

PROD

**Comment by janmedrek** [comment]
Closing in favor of: https://github.com/kyma-project/lifecycle-manager/issues/1491
