### ISSUE TITLE
[PROD] KLM panicked with `runtime error: invalid memory address or nil pointer dereference` 

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1489]
### Description

**Since there are several caches in the KLM all should be checked for this bug**

Dashboards showed a drop in memory and CPU usage at 2024-04-18T06:37 UTC:
<img width="952" alt="image" src="https://github.com/kyma-project/lifecycle-manager/assets/22994291/8f9240a9-7266-4da7-8150-52931554e683">

The pod (`klm-controller-manager-6fcd9777cd-vb2ld`) has been re-started:

```
Apr 18, 2024 @ 06:37:21.877starting Lifecycle-Manager version: from_dockerfile
```

Reason for this is that there has been a panic due to invalid memory address / nil pointer:

```
Apr 18, 2024 @ 06:37:21.511 - sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000324a00, {0x383b6e0, 0xc000774a50})
Apr 18, 2024 @ 06:37:21.511 - sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
Apr 18, 2024 @ 06:37:21.511 - /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227 +0x79
Apr 18, 2024 @ 06:37:21.511 - created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 368
Apr 18, 2024 @ 06:37:21.511 - /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:316 +0x3bc
Apr 18, 2024 @ 06:37:21.511 - /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266 +0x1be
Apr 18, 2024 @ 06:37:21.511 - /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:223 +0x50c
Apr 18, 2024 @ 06:37:21.510 - github.com/kyma-project/lifecycle-manager/internal/declarative/v2.(*Reconciler).Reconcile(0xc00080a960, {0x383b6a8, 0xc1029e4900}, {{{0xc124d58686?, 0x5?}, {0xc091140880?, 0xc0d34bdd10?}}})
Apr 18, 2024 @ 06:37:21.510 - /workspace/internal/declarative/v2/reconciler.go:155 +0x86c
Apr 18, 2024 @ 06:37:21.510 - /workspace/internal/declarative/v2/reconciler.go:587 +0xbc
Apr 18, 2024 @ 06:37:21.510 - /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:119 +0xb7
Apr 18, 2024 @ 06:37:21.510 - sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x3848ce0?, {0x383b6a8?, 0xc1029e4900?}, {{{0xc124d58686?, 0xb?}, {0xc091140880?, 0x0?}}})
Apr 18, 2024 @ 06:37:21.510 - sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000324a00, {0x383b6e0, 0xc000774a50}, {0x2f34f80, 0xc0a0150660})
Apr 18, 2024 @ 06:37:21.509 - github.com/jellydator/ttlcache/v3.(*Item[...]).Value(0x387fa80?)
Apr 18, 2024 @ 06:37:21.509 - /go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.2.0/item.go:131 +0x29
Apr 18, 2024 @ 06:37:21.509 - github.com/kyma-project/lifecycle-manager/internal/declarative/v2.(*Reconciler).getTargetClient(0xc00080a960, {0x383b6a8, 0xc1029e4900}, {0x3873028, 0xc00c236f00})
Apr 18, 2024 @ 06:37:21.509 - panic({0x2d397e0?, 0x53f4830?})
Apr 18, 2024 @ 06:37:21.509 - github.com/kyma-project/lifecycle-manager/internal/declarative/v2.(*MemoryClientCache).GetClient(0xc0001cf700, {0xc110cffec0, 0x34})
Apr 18, 2024 @ 06:37:21.509 - /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:116 +0x1e5
Apr 18, 2024 @ 06:37:21.509 - /usr/local/go/src/runtime/panic.go:770 +0x132
Apr 18, 2024 @ 06:37:21.509 - /workspace/internal/declarative/v2/client_cache.go:37 +0x6a
Apr 18, 2024 @ 06:37:21.508 - [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2869529]
Apr 18, 2024 @ 06:37:21.508-
Apr 18, 2024 @ 06:37:21.508 - panic: runtime error: invalid memory address or nil pointer dereference
Apr 18, 2024 @ 06:37:21.508 - sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
Apr 18, 2024 @ 06:37:21.508 - goroutine 679 [running]:
Apr 18, 2024 @ 06:37:21.507 - panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Apr 18, 2024 @ 06:37:21.507 - 2024-04-18T06:37:21.057955033Z stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```

Shortly before, we had significant spikes in:

```
Invalidating manifest-controller client cache entry for key: "[...]"
```

Same occurred on 2024-04-22T13:30UTC

### Steps to reproduce

to be found out

### Environment Type

Managed

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
Kyma CLI Version: x.y.z
If used - k3d/k3s/minikube versions

**Comment by c-pius** [comment]
Problem may be here: https://github.com/kyma-project/lifecycle-manager/blob/main/internal/declarative/v2/client_cache.go#L37

```go
func (m *MemoryClientCache) GetClient(key string) Client {
	ok := m.internal.Has(key)
	if !ok {
		return nil
	}
	return m.internal.Get(key).Value() // <-----------
}
```

We directly access the value without checking for nil. Probably, the cache value gets invalidated between the `Has` check and the subsequent `Get`.
