### ISSUE TITLE
Kyma Alpha Create Module fails for Docker Hub as Container Registry

### ISSUE THREAD

**Issue by muralov** [kyma-project/lifecycle-manager#439]
Kyma Alpha Create Module fails for Docker Hub. Here is the command which fails:

```sh
❯ kyma alpha create module -n kyma-project.io/module/nats --version 0.0.1 --registry registry-1.docker.io/{DOCKERHUB_USER} --nameMapping sha256-digest -c {DOCKERHUB_USER}:{DOCKERHuB_TOKEN} -w
```
The command caused the following error:
```
WARNING: This command is experimental and might change in its final version. Use at your own risk.
- Kustomize ready
? Please specify the file to use as default CR in /Users/I504380/Go/src/github.com/{DOCKERHUB_USER}/nats-manager/config/samples: [kustomization.yaml operator_v1alpha1_nats.yaml]
operator_v1alpha1_nats.yaml
- Module built
- Default CR validation succeeded
- Creating module archive at "./mod"
- Image created
\ Pushing image to "registry-1.docker.io/{DOCKERHUB_USER}"panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d39b56]

goroutine 1 [running]:
io.(*PipeWriter).Write(...)
	/usr/local/go/src/io/pipe.go:165
github.com/containerd/containerd/remotes/docker.(*pushWriter).Commit(0xc00023fdc0, {0x0?, 0x4169d40?}, 0x0, {0xc00062c050, 0x47}, {0xc0f855abf2377030?, 0x3e69242ef?, 0x5b80ea0?})
	/home/prow/go/pkg/mod/github.com/containerd/containerd@v1.6.15/remotes/docker/pusher.go:431 +0x76
github.com/containerd/containerd/content.Copy({0x419bf08, 0xc00019a008}, {0x41a2320, 0xc00023fdc0}, {0x332640f0, 0xc000735600}, 0x0, {0xc00062c050, 0x47}, {0x0, ...})
	/home/prow/go/pkg/mod/github.com/containerd/containerd@v1.6.15/content/helpers.go:176 +0x49f
github.com/kyma-project/cli/pkg/module/oci.(*client).pushContent(0x2?, {0x419bf08, 0xc00019a008}, {0x33264d80?, 0xc000ea8578?}, {0x41763a0, 0xc0006a2510}, {{0xc000623cb0, 0x18}, {0xc00062c050, ...}, ...})
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/oci/client.go:288 +0x37f
github.com/kyma-project/cli/pkg/module/oci.(*client).PushManifest(0xc000500960, {0x419bf08, 0xc00019a008}, {0xc000223c00, 0x63}, 0xc0005ae240)
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/oci/client.go:253 +0xa6b
github.com/kyma-project/cli/pkg/module.Push(0xc0012d7e00, 0xc0004e3b30, 0xc00059d068)
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/remote.go:75 +0x65d
github.com/kyma-project/cli/cmd/kyma/alpha/create/module.(*command).Run(0xc000a7f2c0, {0x0?, 0x0?, 0x0?})
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/alpha/create/module/module.go:172 +0x6a5
github.com/kyma-project/cli/cmd/kyma/alpha/create/module.NewCmd.func1(0xc000162900?, {0xc000bb3080?, 0xb?, 0xb?})
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/alpha/create/module/module.go:61 +0x25
github.com/spf13/cobra.(*Command).execute(0xc000162900, {0xc000bb2fd0, 0xb, 0xb})
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d16600)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/prow/go/src/github.com/kyma-project/cli/cmd/main.go:13 +0x57
```

**Comment by janmedrek** [comment]
Hey @muralov, I can see the `registry-1.docker.io/{DOCKERHUB_USER}` as a push target, is this variable set? We will implement some sort of fallback to not panic in that case and check whether CLI resolves those values correctly.

If you would like to see the support for that variable then please create the issue and explain where it comes from and how to handle that.

**Comment by muralov** [comment]
yes, I had my DockerHub username set as it follows:
`kyma alpha create module -n kyma-project.io/module/nats --version 0.0.1 --registry registry-1.docker.io/myuser --nameMapping sha256-digest -c myuser:my-token -w`

**Comment by medmes** [comment]
Thanks @muralov , but the thing on my machine is the `--nameMapping` flag is unknown, i tried with to replace it with -n and it worked but again the `-w` flag is not recognised.

I also tried to use the latest kyma cli from `main` branch and it's not reproducible as well

**Comment by medmes** [comment]
Again, the issue is not reprodicible. As at the moment we have missing inputs.

I tried to modify the command as a way to reproduce it as well with the latest changes (main branch):
` ./bin/kyma-darwin alpha create module -n kyma-project.io/module/nats --version 0.0.1 --registry registry-1.docker.io/{DOCKERHUB_USER} --name-mapping sha256-digest -c {DOCKERHUB_USER}:{DOCKERHuB_TOKEN}`

**The output is:** 

```
WARNING: This command is experimental and might change in its final version. Use at your own risk.
- Module built (1ms)
- Default CR validation succeeded (0s)
- Module archive created (7ms)
- Adding layers to archive... (8.544s)
X Pushing image to "registry-1.docker.io/{DOCKERHUB_USER}" (2.875s)
Error: could not finish component transfer: kyma-project.io/module/nats:v0.0.1: transferring resource 0: unable to add blob: unable to add blob: failed to push: unexpected status: 404 Not Found
```

I believe this error's coming from docker library when the repository is not exist on the registry, but again we re missing more details in order to replicate the same command output.
